### ISSUE TITLE
Not work for me

### ISSUE THREAD

**Issue by oghmios** [cgkineo/adapt-audio#1]
I can't use that extension. I put the code in components.json, and I see the icon in my course, but when I click in the button, it returns me to index page.

I put the correct URL to mp3 archive

**Comment by moloko** [comment]
You also need to modify the JavaScript code for the component(s) you want to use the audio extension with, as documented in the Usage section of the [README](https://github.com/cgkineo/adapt-audio/blob/master/README.md#usage)

**Comment by oghmios** [comment]
I put the code as a README in component's text .js, but it's the same. I need to put inside the function or like a new function?

**Comment by moloko** [comment]
You first need to listen to the `click` event of the audio controls.

If the component you're adding the controls to has an [events hash](http://backbonejs.org/#View-events) then you can add this to it:

```
'click .audio-controls .icon':'onAudioButtonClicked'
```

(If it doesn't have an events hash you can either add one or use whatever other method of listening to dom events takes your fancy)

You can then add a (new) function like this:

```
onAudioButtonClicked:function(event) {
    if(event) event.preventDefault();

    Adapt.trigger('audio', event.currentTarget);
}
```

**Comment by moloko** [comment]
I've updated the README a bit for clarity

**Comment by moloko** [comment]
@oghmios can I close this off now?

**Comment by oghmios** [comment]
Yes, thank you for all
