### ISSUE TITLE
Autoplay and autostop

### ISSUE THREAD

**Issue by oghmios** [cgkineo/adapt-audio#2]
Hi, I'm using your extension with articleBlockSlider, and I will do that when I change the slide( change to a new block), the previous audio stop and new audio play automatically.

Is it possible?

**Comment by moloko** [comment]
Yes but you'll have to modify articleBlockSlider a fair bit to get it to work.

Also note that autoplay is disabled at an OS level on iOS so it could be challenging getting that to work... you need to make sure the code to start the audio is directly associated with the user clicking something or it will be blocked.

**Comment by oghmios** [comment]
Thank you for all

**Comment by oghmios** [comment]
I understand that you are saying me, but I don't know how call any method of audio.js from blockslider.js. Do I need to create an instance or how i can call a, for example, function play() from blockslider.js?

I'm beginner in javascript and i'm learning now.

**Comment by oliverfoster** [comment]
As Matt has said, auto-play is a very bad idea. You can get the player to stop any time by putting `Adapt.trigger("audio:stop");` at the point in the blockslider where you want the audio to stop. It is recommended to have the user hit the play button themselves and not do auto play. The support for auto play is bad.

**Comment by oghmios** [comment]
Ok, I know that auto-play is a bad idea, but I was asked to do so.

Thank you for all
