### ISSUE TITLE
Problems with the feedback description

### ISSUE THREAD

**Issue by dannepop** [cgkineo/adapt-audio#4]
It seems like the new version of adapt is structured different then the version described here! 

The feedback instructions is not useable! For instance there is no tutor.hbs no longer. I think that it´s replaced by the notification.hbs. 

I can´t figure out how to use the information on feedback here. 
Can someone update this for the current version of adapt! 
Please!
Best Danne/

**Comment by moloko** [comment]
hi @dannepop instructions should be the same - except you modify [notify.hbs](https://github.com/adaptlearning/adapt_framework/blob/master/src/core/templates/notify.hbs) instead of tutor.hbs

**Comment by dannepop** [comment]
There are two different notify handlebar files. One in the core and one in themes. 
And could you help with were to place the "{{> audio-controls feedbackAudio}}" in the notify.hbs

**Comment by moloko** [comment]
@dannepop it's the one in the theme you need to change. I've also updated the README to amend the 'usage with other extensions' section to reflect that the code that needs to be changed is in questionModel.js as of Adapt 2.0.10
