### ISSUE TITLE
Can provide a properties.schema for uploading this plugin to adapt authoring tool 0.10.5 & adapt framework 5.7.0?

### ISSUE THREAD

**Issue by futurexiong** [cgkineo/adapt-audio#9]
Can't use this plugin in adapt authoring tool
`adapt install adapt-audio
Fatal error: please run above commands in adapt course directory.`
or
![QQ20200929-143349](https://user-images.githubusercontent.com/1567478/94521551-d8a8f700-0260-11eb-9099-b4b36b5841c9.png)

**Comment by moloko** [comment]
@futurexiong sorry but there's really no way to make this plugin authoring tool compatible in its current format. if you have a look at the usage instructions in the README it should be pretty clear that it can't just be 'plugged in', it requires some pretty significant modifications to the core code to make it work
